# Generated by Django 3.0.8 on 2020-11-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, 'NEWEST ARTICLE'), (3, 'HOTEST ARTICLE'), (4, 'NEWEST COMMENTS')], default=1, verbose_name='display type'),
        ),
    ]
