# Generated by Django 3.1.3 on 2020-11-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20201103_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'SHOW'), (0, 'HIDE')], db_index=True, default=1, verbose_name='status'),
        ),
    ]
