# Generated by Django 3.1.3 on 2020-11-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'NORMAL'), (0, 'DELETE'), (2, 'DRAFT')], db_index=True, default=1, verbose_name='status'),
        ),
    ]
