# Generated by Django 3.1.3 on 2020-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201107_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'NORMAL'), (0, 'DELETE')], db_index=True, default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'NORMAL'), (0, 'DELETE')], db_index=True, default=1, verbose_name='status'),
        ),
    ]
