# Generated by Django 3.1.3 on 2020-11-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201107_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_nav',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is_nav'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(db_index=True, default=False, verbose_name='markdown'),
        ),
    ]
